apiVersion: state.yndd.io/v1alpha1
kind: State
metadata:
  name: state-itfce-leaf1
  namespace: ndd-system
spec:
  lifecycle:
    deploymentPolicy: active
    deletionPolicy: delete
  targetRef:
    name: leaf1.sim.1a-b0-02-ff-00-00
  properties:
    name: interface
    prefix: itfce
    path:
    - /interface[name=*]/oper-state
    - /interface[name=*]/subinterface[index=*]/oper-state