apiVersion: state.nddp.yndd.io/v1alpha1
kind: State
metadata:
  name: state-itfce-leaf1
  namespace: default
spec:
  deploymentPolicy: Active
  deletionPolicy: Delete
  networkNodeRef:
    name: leaf1
  properties:
    name: interface
    prefix: itfce
    description: interface-state-collector
    admin-state: enable
    path:
    - /interface[name=*]/oper-state
    - /interface[name=*]/subinterface[index=*]/oper-state