apiVersion: meta.pkg.ndd.yndd.io/v1
kind: Provider
metadata:
  name: state-worker
  namespace: ndd-system
spec:
  pod:
    name: state-worker
    type: statefulset
    permissionRequests:
    - apiGroups: [target.yndd.io]
      resources: [targets, targets/status]
      verbs: [get, list, watch, update, patch, create, delete]
    containers:
    - container:
        name: kube-rbac-proxy
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
        args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        ports:
        - containerPort: 8443
          name: https
    - container:
        name: worker
        image: yndd/state-worker-controller:latest
      extras:
        - {name: grpc, service: true, certificate: true, port: 9999, target-port: 9999}
        - {name: metrics, service: true,  port: 8443, target-port: 443}
        - {name: profiler, volume: true}
