apiVersion: meta.pkg.ndd.yndd.io/v1
kind: Provider
metadata:
  name: state-reconciler
  namespace: ndd-system
spec:
  pod:
    name: state-reconciler
    type: statefulset
    permissionRequests:
    - apiGroups: ["*"]
      resources: [secrets]
      verbs: [get, list, watch]
    - apiGroups: ["*"]
      resources: [events]
      verbs: [get, list, watch, update, patch, create, delete]
    - apiGroups: [target.yndd.io]
      resources: [targets, targets/status]
      verbs: [get, list, watch]
    - apiGroups: [target.yndd.io]
      resources: [targetusages]
      verbs: [get, list, watch, update, patch, create, delete]
    containers:
    - container:
        name: kube-rbac-proxy
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
        args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        ports:
        - containerPort: 8443
          name: https
    - container:
        name: controller
        image: registry.yndd.io/yndd/state-reconciler-controller:latest
      extras:
        - {name: webhook, webhook: true, service: true, certificate: true, port: 443, targetPort: 9443}
        - {name: grpc, service: true, certificate: true, port: 9999, targetPort: 9999}
        - {name: metrics, service: true, port: 8443, targetPort: 443}
        - {name: profiler, volume: true}