name: golangci-lint
on:
  workflow_dispatch:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          args: --timeout=3m
      
