name: Test

on:
  workflow_dispatch: {}
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.9
        
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    - name: Build
      run: go build -v ./...

    - name: Run coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic -v ./...
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2

        # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
        # skip-build-cache: true

    - name: Staticcheck
      run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...
    